function addpath_FMMtools()
        
    if ~isdeployed    
            thisdir = fileparts( mfilename( 'fullpath' ) );
            addpath( thisdir,...
                    [thisdir filesep 'Classes'],...
                    [thisdir filesep 'HelperFunctions'],...
                    [thisdir filesep 'HelperFunctions' filesep 'xml_io_tools'],...
                    [thisdir filesep 'HelperFunctions' filesep 'FastICA_25'],...                                                        
                    [thisdir filesep 'GUIDEInterfaces']); 
    end
            
end