function addpath_FMMtools()
        
    if ~isdeployed    
            thisdir = fileparts( mfilename( 'fullpath' ) );
            addpath( thisdir,...
                    [thisdir filesep 'Classes'],...
                    [thisdir filesep 'HelperFunctions'],...                
                    [thisdir filesep 'HelperFunctions' filesep 'xml_io_tools'],...                
                    [thisdir filesep 'GUIDEInterfaces']); 
    end
            
end